export const html = `https://i.postimg.cc/fRbKFQ8X/Html.png`;
export const css = `https://i.postimg.cc/VNpDnZBt/Css.png`;
export const react = `https://i.postimg.cc/mkwYXmM8/react.png`;
export const redux = `https://i.postimg.cc/yYpMS1P5/redux-logo.png`;
export const js = `https://cdn.pixabay.com/photo/2015/04/23/17/41/javascript-736400_960_720.png`;
export const git = `https://i.postimg.cc/hPcMLdx2/git.png`;
export const github = `https://i.postimg.cc/rySQRJdd/github.png`;
export const typescript = `https://i.postimg.cc/4Nfb7TkM/typescript.png`;
export const cypress = `https://i.postimg.cc/sx9mFjFP/cypress1.webp`;
export const chakra = `https://i.postimg.cc/BnhhQnjM/chakra.png`;
export const express = `https://i.postimg.cc/G2DzQPq5/express.png`;
export const vs = `https://i.postimg.cc/CKqjThkZ/vscode.png`;
export const dsa = `https://i.postimg.cc/15BBJ3rs/Dsa.png`;
export const postman = `https://cdn.worldvectorlogo.com/logos/postman.svg`;
export const mongo =`https://i.postimg.cc/SsTyyczf/leaf.png`
// export const thunder = `https://rangav.gallerycdn.vsassets.io/extensions/rangav/vscode-thunder-client/2.6.2/1681222207111/Microsoft.VisualStudio.Services.Icons.Default`;
export const next=`https://i.postimg.cc/NjMxNH6v/Icon-dark-background.png`;
export const hostinger=`https://i.postimg.cc/y8Ldt96s/Hostinger-Logo-4-K.png`;
export const gpt=`https://i.postimg.cc/Bv5Nfz0F/640px-Chat-GPT-logo-svg.png`;
export const tailwind=`https://i.postimg.cc/DzCrsXnm/512px-Tailwind-CSS-Logo-svg-1.png`